Repository openpoke/decidim-module-reporting-proposals, pull requests merged in 2022-09, with the labels that each got.

#7 Add due dates for unanswered/unevaluated proposals
  app/controllers/concerns/decidim/reporting_proposals/admin/needs_header_snippets.rb
  app/helpers/concerns/decidim/reporting_proposals/admin/proposals_helper_override.rb
  app/packs/entrypoints/decidim_reporting_proposals_component_admin.js
  app/packs/entrypoints/decidim_reporting_proposals_list_component_admin.js
  app/packs/entrypoints/decidim_reporting_proposals_manage_component_admin.js
  app/packs/stylesheets/decidim/reporting_proposals/list_component_admin.scss
  app/packs/stylesheets/decidim/reporting_proposals/manage_component_admin.scss
  app/views/decidim/proposals/admin/proposals/_proposal-tr.html.erb
  config/assets.rb
  config/i18n-tasks.yml
  config/locales/en.yml
  lib/decidim/reporting_proposals.rb
  lib/decidim/reporting_proposals/component.rb
  lib/decidim/reporting_proposals/config.rb
  lib/decidim/reporting_proposals/engine.rb
  spec/lib/overrides_spec.rb
  spec/system/admin/overdue_proposal_spec.rb
  spec/system/shared/admin_proposals_overdue_examples.rb
Labels: REF06

#8 Hide proposals without reporting
  Gemfile.lock
  app/commands/decidim/reporting_proposals/create_report_override.rb
  app/controllers/decidim/reporting_proposals/admin/application_controller.rb
  app/controllers/decidim/reporting_proposals/admin/proposals_controller.rb
  app/permissions/decidim/reporting_proposals/admin/permissions.rb
  app/permissions/decidim/reporting_proposals/permissions.rb
  app/views/decidim/proposals/admin/proposals/_proposal-tr.html.erb
  config/locales/en.yml
  lib/decidim/reporting_proposals.rb
  lib/decidim/reporting_proposals/admin.rb
  lib/decidim/reporting_proposals/admin_engine.rb
  lib/decidim/reporting_proposals/config.rb
  lib/decidim/reporting_proposals/engine.rb
  spec/controllers/admin/proposals_controller_spec.rb
  spec/lib/overrides_spec.rb
  spec/system/admin/report_and_hide_proposals_spec.rb
Labels: REF08

#12 Allow geolocation fields to "Use my location"
  app/commands/concerns/decidim/reporting_proposals/create_report_override.rb
  app/controllers/decidim/reporting_proposals/application_controller.rb
  app/controllers/decidim/reporting_proposals/geolocation_controller.rb
  app/forms/concerns/decidim/reporting_proposals/map_builder_override.rb
  app/packs/entrypoints/decidim_reporting_proposals_geocoding.js
  app/packs/src/decidim/reporting_proposals/reverse_geocoding.js
  app/packs/stylesheets/decidim/reporting_proposals/geocoding_addons.scss
  app/permissions/decidim/reporting_proposals/permissions.rb
  config/assets.rb
  config/locales/en.yml
  lib/decidim/reporting_proposals/config.rb
  lib/decidim/reporting_proposals/engine.rb
  spec/commands/create_report_spec.rb
  spec/controllers/geolocation_controller_spec.rb
  spec/lib/overrides_spec.rb
  spec/system/admin/report_and_hide_proposals_spec.rb
  spec/system/device_location_spec.rb
Labels: REF17

#13 Add "image from camera" button in file uploads
  app/forms/concerns/decidim/reporting_proposals/form_builder_override.rb
  app/forms/decidim/reporting_proposals/proposal_form.rb
  app/packs/entrypoints/decidim_reporting_proposals_camera.js
  app/packs/src/decidim/reporting_proposals/user_camera_inputs.js
  app/packs/stylesheets/decidim/reporting_proposals/user_camera_inputs.scss
  app/views/decidim/reporting_proposals/proposals/_reporting_proposal_fields.html.erb
  config/assets.rb
  config/locales/en.yml
  lib/decidim/reporting_proposals/component.rb
  lib/decidim/reporting_proposals/config.rb
  lib/decidim/reporting_proposals/engine.rb
  spec/forms/proposal_form_spec.rb
  spec/lib/overrides_spec.rb
  spec/system/device_camera_spec.rb
  spec/system/device_location_spec.rb
  spec/system/reporting_proposals_spec.rb
  spec/system/shared/proposals_steps_examples.rb
Labels: REF15
